---
# tasks file for compose-install

- name: Install docker if not already installed
  include_role:
    name: geerlingguy.docker
    tasks_from: install
  when: docker_install_docker_need_install

- name: Make /opt/backrest directory
  file:
    dest: /opt/backrest
    state: directory
    owner: root
    group: root
    mode: "0755"
- name: Template the docker-compose file
  template:
    src: backrest-compose.yaml.j2
    dest: /opt/backrest/docker-compose.yaml
    owner: root
    group: root
    mode: "0644"

- name: Start the backrest container compose
  community.docker.docker_compose_v2:
    project_src: /opt/backrest
    state: present
    recreate: auto
  when: docker_install_mode == "compose"

- name: Start the backrest container stack
  community.docker.docker_stack:
    state: present
    composefiles:
      - /opt/backrest/docker-compose.yaml
  when: docker_install_mode == "stack"

- name: Template config to /opt/backrest/tmp_config.json
  ansible.builtin.template:
    src: backrest-config.json.j2
    dest: /opt/backrest/tmp_config.json
    owner: root
    group: root
    mode: "0644"
  vars:
    repos: "{{ repos }}"

- name: List all containers
  community.docker.docker_host_info:
    containers: true
  register: docker_containers

- name: Find exact backrest container
  set_fact:
    backrest_container: "{{ item }}"
  with_items: "{{ docker_containers.containers }}"

  when: item.Image == "lpicode/backrest-docker:latest"
- name: Copy config inside the container
  community.docker.docker_container_copy_into:
    path: /opt/backrest/tmp_config.json
    container_path: /config/config.json
    container: "{{ backrest_container.Id }}"

- name: Restart the backrest container
  community.docker.docker_container:
    name: "{{ backrest_container.Id }}"
    state: stopped
  when: backrest_container is defined

- name: Restart the backrest container
  community.docker.docker_container:
    name: "{{ backrest_container.Id }}"
    state: started
  when: backrest_container is defined